**Data Structures**

- List
- Tuple
- Set
- Dictionary

- Mutable
- Immutable

In [1]:
# creating a list
fruits = ["apple", "banana", "mango"]
print(fruits)

['apple', 'banana', 'mango']


In [ ]:
# Accessing items using index
print(fruits[0])  # prints the first element of the list

apple


In [3]:
# Change an element
fruits[2] = "orange"
print(fruits)  # prints the updated list

['apple', 'banana', 'orange']


In [8]:
a = [1, 2, 3.5, False, "word"]
print(a)  # prints the list with mixed data types

[1, 2, 3.5, False, 'word']


In [9]:
a.append("apple")
print(a)

[1, 2, 3.5, False, 'word', 'apple']


In [10]:
a.remove("word")
print(a)

[1, 2, 3.5, False, 'apple']


In [11]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [13]:
for num in range(0,10):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [14]:
#loops through a list
fruits = ["apple", "banana", "mango"]
for fruits in fruits:
    print(fruits)

apple
banana
mango


In [16]:
colours = ("red", "green", "blue")
print(colours[0])  # prints the first element of the list
print(type(colours))  # prints the type of the variable, which is a list

red
<class 'tuple'>


In [17]:
#converting to a tuple
a = [1, 2, 3.5, False, "word"]
b = tuple(a)
print(type(b))
print(type(a))

print(b)
print(a)

<class 'tuple'>
<class 'list'>
(1, 2, 3.5, False, 'word')
[1, 2, 3.5, False, 'word']


In [4]:
import numpy as np
a = np.array([1, 2, 3.5])
b = np.array([2,4,5])

print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Cross Product",np.cross(a,b))

Addition [3.  6.  8.5]
Subtraction [-1.  -2.  -1.5]
Multiplication [ 2.   8.  17.5]
Division [0.5 0.5 0.7]
Cross Product [-4.  2.  0.]


**Reshaping and Flattening**

In [5]:
arr = np.arange(1,10) 
reshaped = arr.reshape(3,3)
flattened = reshaped.flatten()
print(arr)
print("-----------")
print(reshaped)
print(flattened)

[1 2 3 4 5 6 7 8 9]
-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
