In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.3


In [5]:
print(1_000_000.0)

1000000.0


**Compare list and numpy array**

In [ ]:
import time
import numpy as np
n = 1_000_000

py_list = list(range(n))
np_array = np.arange(n)

print(len(py_list))
print(len(np_array))ad

1000000
1000000


In [4]:
import time
import numpy as np

n = 1000000

# ---------------- Python List ----------------
t1 = time.time()

py_list = [i**2 for i in range(n)]

t2 = time.time()

print("Python List first 10:", py_list[:10])
print("Python List Time:", t2 - t1)


# ---------------- NumPy Array ----------------
t1 = time.time()

np_array = np.arange(n)**2

t2 = time.time()

print("NumPy Array first 10:", np_array[:10])
print("NumPy Array Time:", t2 - t1)

Python List first 10: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Python List Time: 0.031584978103637695
NumPy Array first 10: [ 0  1  4  9 16 25 36 49 64 81]
NumPy Array Time: 0.009843111038208008


In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
arr3 = np.array([[[2,3,4], [5,6,7], [7,8,9]]])
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)

Array 1: [1 2 3]
Array 2: [[4 5 6]
 [7 8 9]]
Array 3: [[[2 3 4]
  [5 6 7]
  [7 8 9]]]


In [11]:
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
